"""Generic async CRUD repository bound to a single ORM model."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Generic, TypeVar

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from maya_domain.core.errors import NotFoundError
from maya_domain.database.base import Base

ModelT = TypeVar("ModelT", bound=Base)


class BaseRepository(Generic[ModelT]):
    """Generic data-access object providing common CRUD operations.

    Subclasses set the ``model`` class attribute to the concrete ORM model
    they operate on. Mutating methods flush the session so autogenerated
    primary keys and constraint violations surface immediately, but never
    commit -- the caller (or a unit-of-work) owns the transaction boundary.
    """

    model: type[ModelT]

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    async def get(self, id: int) -> ModelT | None:
        """Return the row with the given primary key, or ``None``."""
        return await self.session.get(self.model, id)

    async def get_or_404(self, id: int) -> ModelT:
        """Return the row with the given primary key or raise :class:`NotFoundError`."""
        obj = await self.get(id)
        if obj is None:
            raise NotFoundError(f"{self.model.__name__} {id} not found")
        return obj

    async def list(self, *, limit: int = 100, offset: int = 0) -> Sequence[ModelT]:
        """Return up to ``limit`` rows starting at ``offset``."""
        stmt = select(self.model).limit(limit).offset(offset)
        result = await self.session.execute(stmt)
        return result.scalars().all()

    async def add(self, obj: ModelT) -> ModelT:
        """Add an already-constructed instance to the session and flush."""
        self.session.add(obj)
        await self.session.flush()
        return obj

    async def create(self, **values: Any) -> ModelT:
        """Construct a new instance from ``values``, add it, and flush."""
        obj = self.model(**values)
        return await self.add(obj)

    async def update(self, obj: ModelT, **values: Any) -> ModelT:
        """Apply ``values`` to ``obj`` and flush."""
        for key, value in values.items():
            setattr(obj, key, value)
        await self.session.flush()
        return obj

    async def delete(self, obj: ModelT) -> None:
        """Delete ``obj`` and flush."""
        await self.session.delete(obj)
        await self.session.flush()
