"""phase 2 initial schema

Revision ID: d846db38157f
Revises: 
Create Date: 2026-07-18 00:06:06.873325

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd846db38157f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_ts > start_ts', name=op.f('ck_availability_end_after_start')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability'))
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index('ix_availability_start_ts_is_booked', ['start_ts', 'is_booked'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=True)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'cancelled', 'completed', 'no_show', name='appointmentstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['availability_id'], ['availability.id'], name=op.f('fk_appointments_availability_id_availability')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments')),
    sa.UniqueConstraint('availability_id', name=op.f('uq_appointments_availability_id'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)

    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('completed', 'dropped', 'escalated', 'booked', name='calloutcome'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_call_logs_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_logs'))
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_logs_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_room_name'), ['room_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_started_at'), ['started_at'], unique=False)

    op.create_table('callbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('normal', 'urgent', 'emergency', name='callbackpriority'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'resolved', name='callbackstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_callbacks_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callbacks'))
    )
    with op.batch_alter_table('callbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callbacks_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_callbacks_status_priority', ['status', 'priority'], unique=False)

    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_log_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'assistant', 'system', 'tool', name='conversationrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], name=op.f('fk_conversation_history_call_log_id_call_logs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_history'))
    )
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_history_call_log_id'), ['call_log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_history_call_log_id'))

    op.drop_table('conversation_history')
    with op.batch_alter_table('callbacks', schema=None) as batch_op:
        batch_op.drop_index('ix_callbacks_status_priority')
        batch_op.drop_index(batch_op.f('ix_callbacks_patient_id'))

    op.drop_table('callbacks')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_started_at'))
        batch_op.drop_index(batch_op.f('ix_call_logs_room_name'))
        batch_op.drop_index(batch_op.f('ix_call_logs_patient_id'))

    op.drop_table('call_logs')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_phone'))

    op.drop_table('patients')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index('ix_availability_start_ts_is_booked')

    op.drop_table('availability')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
